Repository ittory-project/ittory-client, pull requests merged in 2025-03, with the labels that each got.

#240 Fix: RL1M-235 로그인 페이지 1차 디자인 QA 반영
  public/assets/kakao_logo.png
  public/assets/login/kakao_bubble.svg
  src/components/loginPage/Login.tsx
  src/index.css
  src/pages/home/LoginPage.tsx
Labels: 🐞 BugFix

#239 Design: RL1M-234 생성된 편지 디자인 QA 반영
  .github/pull_request_template.md
  src/components/InvitePage/Count/Count.tsx
  src/components/InvitePage/Member.tsx
  src/components/createPage/CoverDeco/ImageCropper.tsx
  src/pages/invite/LoadingPage.tsx
Labels: 🎨 Design

#242 Chore: RL1M-236 Package.json 의존성 관리 및 Github Security Issues 작업
  .gitignore
  .node-version
  package-lock.json
  package.json
Labels: 🔨 Chore

#245 Fix: RL1M-250 참여하기 닉네임 스페이스바 처리
  src/components/joinPage/Join.tsx
Labels: 🐞 BugFix

#248 Fix: RL1M-252 참여 로직 수정
  package-lock.json
  src/api/model/LetterModel.ts
  src/api/service/LetterService.ts
  src/components/joinPage/Join.tsx
  src/components/joinPage/JoinModal.tsx
Labels: 🐞 BugFix
